# Generated by Django 6.0.3 on 2026-04-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='email',
        ),
    ]
